package main

import (
	"github.com/alecthomas/kong"
)

type CLI struct {
	DecodeResponse        DecodeResponseCmd        `cmd:"" help:"Decodes encrypted response sent by PTD server."`
	DecodeSaveData        DecodeSaveDataCmd        `cmd:"" help:"Decodes local save data to JSON."`
	EncodeSaveData        EncodeSaveDataCmd        `cmd:"" help:"Encodes local save data back to encrypted BSON."`
	DecodeMD              DecodeMDCmd              `cmd:"" help:"Decodes MD."`
	GenerateLoginResponse GenerateLoginResponseCmd `cmd:"" help:"Generates Login.json."`
}

func main() {
	cli := CLI{}

	ctx := kong.Parse(&cli,
		kong.Name("ptd-tool"),
		kong.Description("Decodes encrypted data files generated by PTD."),
		kong.UsageOnError(),
		kong.ConfigureHelp(kong.HelpOptions{
			Compact: true,
			Summary: true,
		}))
	err := ctx.Run()
	ctx.FatalIfErrorf(err)
}
